"""Explicit Google Health persistence for R04. No live OAuth or sync."""

from healthcheck.db.models import (
    GoogleMetricState,
    GooglePayloadStatus,
    GoogleQueryMode,
    GoogleSourceKind,
)
from healthcheck.google.contracts import (
    FAMILY_ALL_SOURCES,
    FAMILY_GOOGLE_SOURCES,
    FAMILY_GOOGLE_WEARABLES,
    GOOGLE_INPUT_METHOD,
    GOOGLE_PROVIDER_CODE,
    GOOGLE_SOURCE_APPLICATION,
    NORMALIZATION_CONTRACT_VERSION,
    OBSERVATION_KEY_VERSION,
    PERSISTENCE_CONTRACT_VERSION,
    SOURCE_CONTRACT_VERSION,
    GoogleMetricDTO,
    GoogleQueryContext,
    GoogleRecordDTO,
    GoogleSourceIdentity,
    GoogleStream,
    GoogleTemporalDTO,
    GoogleTemporalPrecision,
)
from healthcheck.google.persistence import (
    GooglePayloadObservationRepository,
    GooglePersistenceOutcome,
    GooglePersistenceRepository,
    GoogleRawPayloadRepository,
    GoogleSourceRecordRepository,
    GoogleSourceRepository,
    build_google_observation_key,
    build_google_record_identity_key,
    google_persistence_for,
)
from healthcheck.google.storage import (
    ContentAddressedGooglePayloadStore,
    StoredGooglePayload,
    serialize_google_payload,
)

__all__ = [
    "FAMILY_ALL_SOURCES",
    "FAMILY_GOOGLE_SOURCES",
    "FAMILY_GOOGLE_WEARABLES",
    "GOOGLE_INPUT_METHOD",
    "GOOGLE_PROVIDER_CODE",
    "GOOGLE_SOURCE_APPLICATION",
    "NORMALIZATION_CONTRACT_VERSION",
    "OBSERVATION_KEY_VERSION",
    "PERSISTENCE_CONTRACT_VERSION",
    "SOURCE_CONTRACT_VERSION",
    "ContentAddressedGooglePayloadStore",
    "GoogleMetricDTO",
    "GoogleMetricState",
    "GooglePayloadObservationRepository",
    "GooglePayloadStatus",
    "GooglePersistenceOutcome",
    "GooglePersistenceRepository",
    "GoogleQueryContext",
    "GoogleQueryMode",
    "GoogleRawPayloadRepository",
    "GoogleRecordDTO",
    "GoogleSourceIdentity",
    "GoogleSourceKind",
    "GoogleSourceRecordRepository",
    "GoogleSourceRepository",
    "GoogleStream",
    "GoogleTemporalDTO",
    "GoogleTemporalPrecision",
    "StoredGooglePayload",
    "build_google_observation_key",
    "build_google_record_identity_key",
    "google_persistence_for",
    "serialize_google_payload",
]
